server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanted?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.default_batch_fetch_size]": 100
      "[hibernate.format_sql]": true
      show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    "[com.wanted.backend]": DEBUG
    "[org.hibernate.type]": TRACE
